token:
  signing:
    key: basebasebasebasebasebasebasebasebasebasebasebasebasebasebasebase
spring:
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQL14Dialect
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/Test
    driverClassName: org.postgresql.Driver
    password: '1234'
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: create
log4j:
  appender:
    FILE:
      encoding: UTF-8